// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents.sql

package database

import (
	"context"
	"database/sql"
)

const claimUsername = `-- name: ClaimUsername :one
UPDATE agents
SET username = $2, username_status = 'pending'
WHERE agent_id = $1 AND (username IS NULL OR username_status = 'none')
RETURNING agent_id, root_public_key, username, username_status, created_at
`

type ClaimUsernameParams struct {
	AgentID  string
	Username sql.NullString
}

func (q *Queries) ClaimUsername(ctx context.Context, arg ClaimUsernameParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, claimUsername, arg.AgentID, arg.Username)
	var i Agent
	err := row.Scan(
		&i.AgentID,
		&i.RootPublicKey,
		&i.Username,
		&i.UsernameStatus,
		&i.CreatedAt,
	)
	return i, err
}

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (agent_id, root_public_key)
VALUES ($1, $2)
RETURNING agent_id, root_public_key, username, username_status, created_at
`

type CreateAgentParams struct {
	AgentID       string
	RootPublicKey string
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, createAgent, arg.AgentID, arg.RootPublicKey)
	var i Agent
	err := row.Scan(
		&i.AgentID,
		&i.RootPublicKey,
		&i.Username,
		&i.UsernameStatus,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentByID = `-- name: GetAgentByID :one
SELECT agent_id, root_public_key, username, username_status, created_at FROM agents WHERE agent_id = $1
`

func (q *Queries) GetAgentByID(ctx context.Context, agentID string) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgentByID, agentID)
	var i Agent
	err := row.Scan(
		&i.AgentID,
		&i.RootPublicKey,
		&i.Username,
		&i.UsernameStatus,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentByPublicKey = `-- name: GetAgentByPublicKey :one
SELECT agent_id, root_public_key, username, username_status, created_at FROM agents WHERE root_public_key = $1
`

func (q *Queries) GetAgentByPublicKey(ctx context.Context, rootPublicKey string) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgentByPublicKey, rootPublicKey)
	var i Agent
	err := row.Scan(
		&i.AgentID,
		&i.RootPublicKey,
		&i.Username,
		&i.UsernameStatus,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentByUsernameLower = `-- name: GetAgentByUsernameLower :one
SELECT agent_id, root_public_key, username, username_status, created_at FROM agents WHERE LOWER(username) = LOWER($1)
`

func (q *Queries) GetAgentByUsernameLower(ctx context.Context, lower string) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgentByUsernameLower, lower)
	var i Agent
	err := row.Scan(
		&i.AgentID,
		&i.RootPublicKey,
		&i.Username,
		&i.UsernameStatus,
		&i.CreatedAt,
	)
	return i, err
}
