// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: discovery.sql

package database

import (
	"context"
)

const countApprovedAgents = `-- name: CountApprovedAgents :one
SELECT COUNT(*) FROM agents WHERE username_status = 'approved'
`

func (q *Queries) CountApprovedAgents(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countApprovedAgents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listApprovedAgents = `-- name: ListApprovedAgents :many
SELECT agent_id, root_public_key, username, username_status, created_at
FROM agents
WHERE username_status = 'approved'
ORDER BY username ASC
LIMIT $1 OFFSET $2
`

type ListApprovedAgentsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListApprovedAgents(ctx context.Context, arg ListApprovedAgentsParams) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, listApprovedAgents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.AgentID,
			&i.RootPublicKey,
			&i.Username,
			&i.UsernameStatus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAgentsByUsername = `-- name: SearchAgentsByUsername :many
SELECT agent_id, root_public_key, username, username_status, created_at
FROM agents
WHERE username_status = 'approved'
  AND LOWER(username) LIKE LOWER($1)
ORDER BY username ASC
LIMIT $2 OFFSET $3
`

type SearchAgentsByUsernameParams struct {
	Lower  string
	Limit  int32
	Offset int32
}

func (q *Queries) SearchAgentsByUsername(ctx context.Context, arg SearchAgentsByUsernameParams) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, searchAgentsByUsername, arg.Lower, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.AgentID,
			&i.RootPublicKey,
			&i.Username,
			&i.UsernameStatus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
