// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Agent struct {
	AgentID        string
	RootPublicKey  string
	Username       sql.NullString
	UsernameStatus string
	CreatedAt      time.Time
}

type Message struct {
	MessageID   string
	SenderID    string
	RecipientID string
	Type        string
	Content     json.RawMessage
	CreatedAt   time.Time
	DeliveredAt sql.NullTime
	ReadAt      sql.NullTime
}

type Session struct {
	SessionID        string
	AgentID          string
	SessionPublicKey string
	CreatedAt        time.Time
	ExpiresAt        time.Time
}
