// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Agent struct {
	AgentID        string
	RootPublicKey  string
	Username       sql.NullString
	UsernameStatus string
	CreatedAt      time.Time
}

type Session struct {
	SessionID        string
	AgentID          string
	SessionPublicKey string
	CreatedAt        time.Time
	ExpiresAt        time.Time
}
