// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package database

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (session_id, agent_id, session_public_key, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING session_id, agent_id, session_public_key, created_at, expires_at
`

type CreateSessionParams struct {
	SessionID        string
	AgentID          string
	SessionPublicKey string
	ExpiresAt        time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.SessionID,
		arg.AgentID,
		arg.SessionPublicKey,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.SessionID,
		&i.AgentID,
		&i.SessionPublicKey,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at < NOW() - INTERVAL '1 hour'
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT session_id, agent_id, session_public_key, created_at, expires_at FROM sessions WHERE session_id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, sessionID string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByID, sessionID)
	var i Session
	err := row.Scan(
		&i.SessionID,
		&i.AgentID,
		&i.SessionPublicKey,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
